version: '3.5'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - web
    environment:
      PHP_HOST: web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    environment:
      BG_COLOR: 'black'

  datadog:
    image: datadog/docker-dd-agent
    environment:
     - API_KEY=${DD_API_KEY}
     - TAGS=env:local
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/mounts:/host/proc/mounts:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
