---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
 name: dd-agent
  # namespace: dd-agent

spec:
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
    spec:
      # serviceAccountName: dd-agent
      containers:
      - image: datadog/agent:latest
        imagePullPolicy: Always
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            name: traceport
            protocol: TCP

        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: dd-agent
                key: api-key
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: DD_TAGS
            value: "env:gcp"

        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
