apiVersion: apps/v1
kind: Deployment
metadata:
  name: web

spec:
  selector:
    matchLabels:
      app: web
  template:
    spec:
      containers:
        - name: web
          env:
            - name: BG_COLOR
              value: '#3473b4'
